// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xzuzrscczkzfqnnyrime.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh6dXpyc2Njemt6ZnFubnlyaW1lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1NzU3NzUsImV4cCI6MjA3MzE1MTc3NX0.gVj_B8UO-EWJp0pManuqO7VQjH4DYI59vEkXDQNLET4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});